Dummy app - esqueleto
liafocus/fing-dummy-app-cubeide pull request #1
Opened 2023-12-20 17:01 UTC by liafocus

Modificado proyecto para depender lo menos posible de la HAL de ST.
Por otro lado, se inicializó el SysTickTimer para que interrumpa cada 10 ms. En la interrupción se incrementa un contador que actúa como prescaler para hacer titilar el led.

2023-12-20 17:20 UTC, lmsoria requested changes

2023-12-20 17:20 UTC, lmsoria commented on Core/Inc/gpio.h
> +#ifndef INC_GPIO_H_
La mayoria de los compiladores modernos soport actualmente `#pragma once` como include guard. Es mas comoda que el combo `#ifndef ... #define ... #endif`.

- [ ] Reemplazar include guard por `#pragma once`

2023-12-20 17:20 UTC, lmsoria commented on Core/Inc/gpio.h
> +#endif /* INC_GPIO_H_ */
Cuando se use `#pragma once` no te olvides de borrar esta linea!

2023-12-20 17:20 UTC, lmsoria commented on Core/Inc/rcc.h
> +#ifndef INC_RCC_H_
Idem al comentario anterior sobre las include guards

- [ ] Usar `#pragma once`

2023-12-20 17:20 UTC, lmsoria commented on Core/Src/rcc.c
> +  //if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != 0x00U)
Definiste dos estructuras para configurar el clock y el oscilador, pero nunca fueron configuradas. Habria que copiar el codigo para darle soporte a `HAL_RCC_OscConfig()` y `HAL_RCC_ClockConfig()` en este archivo.

- [ ] Implementar `HAL_RCC_ClockConfig()`
- [ ] Implementar `HAL_RCC_OscConfig()`

2023-12-20 17:20 UTC, lmsoria commented on Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h
> +//#if defined (USE_HAL_DRIVER)
Remover codigo muerto

- [ ] Remover codigo muerto

2023-12-26 17:13 UTC, liafocus commented on Core/Src/rcc.c
> +  //if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != 0x00U)
Resuelto en f705d1133a9130931b25e3e8143f7faec243d0e1

2023-12-26 17:17 UTC, liafocus commented on Core/Inc/rcc.h
> +#ifndef INC_RCC_H_
Resuelto 1d8aa946f5bc549d93a02300e2328f60f97c7547

2023-12-26 17:18 UTC, liafocus commented on Core/Inc/gpio.h
> +#endif /* INC_GPIO_H_ */
Resuelto en 11f11596f43d6ff6e95461bb810a0e8cd6b89773

2023-12-26 17:18 UTC, liafocus commented on Core/Inc/gpio.h
> +#ifndef INC_GPIO_H_
Resuelto en 11f11596f43d6ff6e95461bb810a0e8cd6b89773

2023-12-26 17:19 UTC, liafocus commented on Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h
> +//#if defined (USE_HAL_DRIVER)
Se dejó el archivo original.

2023-12-26 19:42 UTC, lmsoria approved these changes

2023-12-27 13:18 UTC, merged